# Generated by Django 5.1.3 on 2025-02-01 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('type_paiement', models.CharField(choices=[('yas', 'Yas'), ('flooz', 'Flooz')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_produits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('produits', models.ManyToManyField(to='Catalogue.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('produits', models.ManyToManyField(to='Catalogue.produit')),
            ],
        ),
    ]
